INSERT INTO "main"."BOOK"
("Book_name", "TESTAMENT_name")
VALUES ('Genesis', 'OLD TESTAMENT'),('Exodus', 'OLD TESTAMENT'),
('Leviticus', 'OLD TESTAMENT'),('Numbers', 'OLD TESTAMENT'),
('Deuteronomy', 'OLD TESTAMENT'),('Joshua', 'OLD TESTAMENT'),
('Judges', 'OLD TESTAMENT'),('Ruth', 'OLD TESTAMENT'),
('1 Samuel', 'OLD TESTAMENT'),('2 Samuel', 'OLD TESTAMENT'),
('1 Kings', 'OLD TESTAMENT'),
('2 Kings', 'OLD TESTAMENT'),('1 Chronicles', 'OLD TESTAMENT'),
('2 Chronicles', 'OLD TESTAMENT'),('Ezra', 'OLD TESTAMENT'),
('Nehemiah', 'OLD TESTAMENT'),('Esther', 'OLD TESTAMENT'),
('Job', 'OLD TESTAMENT'),('Psalms', 'OLD TESTAMENT'),
('Proverbs', 'OLD TESTAMENT'),('Ecclesiastes ', 'OLD TESTAMENT'),
('Song of Songs ', 'OLD TESTAMENT'),('Isaiah', 'OLD TESTAMENT'),
('Jeremiah', 'OLD TESTAMENT'),('Lamentations', 'OLD TESTAMENT'),
('Ezekiel', 'OLD TESTAMENT'),('Daniel', 'OLD TESTAMENT'),
('Hosea', 'OLD TESTAMENT'),('Joel', 'OLD TESTAMENT'),
('Amos', 'OLD TESTAMENT'),('Obadiah', 'OLD TESTAMENT'),
('Jonah', 'OLD TESTAMENT'),('Micah ', 'OLD TESTAMENT'),
('Nahum', 'OLD TESTAMENT'),('Habakkuk', 'OLD TESTAMENT'),
('Zephaniah', 'OLD TESTAMENT'),('Haggai', 'OLD TESTAMENT'),
('Zechariah', 'OLD TESTAMENT'),('Malachi', 'OLD TESTAMENT'),
('Matthew', 'NEW TESTAMENT'),('Mark', 'NEW TESTAMENT'),
('Luke', 'NEW TESTAMENT'),('John', 'NEW TESTAMENT'),
('Acts', 'NEW TESTAMENT'),('Romans', 'NEW TESTAMENT'),
('1 Corinthians', 'NEW TESTAMENT'),('2 Corinthians', 'NEW TESTAMENT'),
('Galatians', 'NEW TESTAMENT'),('Ephesians', 'NEW TESTAMENT'),
('Philippians', 'NEW TESTAMENT'),('Colossians', 'NEW TESTAMENT'),
('1 Thessalonians', 'NEW TESTAMENT'),('2 Thessalonians', 'NEW TESTAMENT'),
('1 Timothy', 'NEW TESTAMENT'),('2 Timothy', 'NEW TESTAMENT'),
('Titus', 'NEW TESTAMENT'),('Philemon', 'NEW TESTAMENT'),
('Hebrews', 'NEW TESTAMENT'),('James', 'NEW TESTAMENT'),
('1 Peter', 'NEW TESTAMENT'),('2 Peter', 'NEW TESTAMENT'),
('1 John', 'NEW TESTAMENT'),('2 John', 'NEW TESTAMENT'),
('3 John', 'NEW TESTAMENT'),('Jude', 'NEW TESTAMENT'),
('Revelation', 'NEW TESTAMENT');
