CREATE TABLE TESTAMENT(
   TESTAMENT_name VARCHAR(50),
   PRIMARY KEY(TESTAMENT_name)
);

CREATE TABLE BOOK(
   Book_name VARCHAR(100),
   TESTAMENT_name VARCHAR(50) NOT NULL,
   PRIMARY KEY(Book_name),
   FOREIGN KEY(TESTAMENT_name) REFERENCES TESTAMENT(TESTAMENT_name)
);

CREATE TABLE CHAPITER(
   CHAPITER_name COUNTER,
   verse_content TEXT,
   Book_name VARCHAR(100) NOT NULL,
   "CHAPITER_Num" INTEGER,
   PRIMARY KEY(CHAPITER_name),
   FOREIGN KEY(Book_name) REFERENCES LIVRE(Book_name)
);
