INSERT INTO "main"."LIVRE"
("Nom_livre", "NOM_TESTAMENT")
VALUES ('Genèse', 'ANCIEN TESTAMENT'),('Exode', 'ANCIEN TESTAMENT'),
('Lévitique', 'ANCIEN TESTAMENT'),('Nombres', 'ANCIEN TESTAMENT'),
('Deutéronome', 'ANCIEN TESTAMENT'),('Josué', 'ANCIEN TESTAMENT'),
('Juges', 'ANCIEN TESTAMENT'),('Ruth', 'ANCIEN TESTAMENT'),
('1 Samuel', 'ANCIEN TESTAMENT'),('2 Samuel', 'ANCIEN TESTAMENT'),
('1 Rois', 'ANCIEN TESTAMENT'),
('2 Rois', 'ANCIEN TESTAMENT'),('1 Chroniques', 'ANCIEN TESTAMENT'),
('2 Chroniques', 'ANCIEN TESTAMENT'),('Esdras', 'ANCIEN TESTAMENT'),
('Néhémie', 'ANCIEN TESTAMENT'),('Esther', 'ANCIEN TESTAMENT'),
('Job', 'ANCIEN TESTAMENT'),('Psaumes', 'ANCIEN TESTAMENT'),
('Proverbes', 'ANCIEN TESTAMENT'),('Ecclésiaste ', 'ANCIEN TESTAMENT'),
('Cantique ', 'ANCIEN TESTAMENT'),('Esaïe', 'ANCIEN TESTAMENT'),
('Jérémie', 'ANCIEN TESTAMENT'),('Lamentations', 'ANCIEN TESTAMENT'),
('Ezéchiel', 'ANCIEN TESTAMENT'),('Daniel', 'ANCIEN TESTAMENT'),
('Osée', 'ANCIEN TESTAMENT'),('Joël', 'ANCIEN TESTAMENT'),
('Amos', 'ANCIEN TESTAMENT'),('Abdias', 'ANCIEN TESTAMENT'),
('Jonas', 'ANCIEN TESTAMENT'),('Michée ', 'ANCIEN TESTAMENT'),
('Nahum', 'ANCIEN TESTAMENT'),('Habacuc', 'ANCIEN TESTAMENT'),
('Sophonie', 'ANCIEN TESTAMENT'),('Aggée', 'ANCIEN TESTAMENT'),
('Zacharie', 'ANCIEN TESTAMENT'),('Malachie', 'ANCIEN TESTAMENT'),
('Matthieu', 'NOUVEAU TESTAMENT'),('Marc', 'NOUVEAU TESTAMENT'),
('Luc', 'NOUVEAU TESTAMENT'),('Jean', 'NOUVEAU TESTAMENT'),
('Actes', 'NOUVEAU TESTAMENT'),('Romains', 'NOUVEAU TESTAMENT'),
('1 Corinthiens', 'NOUVEAU TESTAMENT'),('2 Corinthiens', 'NOUVEAU TESTAMENT'),
('Galates', 'NOUVEAU TESTAMENT'),('Ephésiens', 'NOUVEAU TESTAMENT'),
('Philippiens', 'NOUVEAU TESTAMENT'),('Colossiens', 'NOUVEAU TESTAMENT'),
('1 Thessaloniciens', 'NOUVEAU TESTAMENT'),('2 Thessaloniciens', 'NOUVEAU TESTAMENT'),
('1 Timothée', 'NOUVEAU TESTAMENT'),('2 Timothée', 'NOUVEAU TESTAMENT'),
('Tite', 'NOUVEAU TESTAMENT'),('Philémon', 'NOUVEAU TESTAMENT'),
('Hébreux', 'NOUVEAU TESTAMENT'),('Jacques', 'NOUVEAU TESTAMENT'),
('1 Pierre', 'NOUVEAU TESTAMENT'),('2 Pierre', 'NOUVEAU TESTAMENT'),
('1 Jean', 'NOUVEAU TESTAMENT'),('2 Jean', 'NOUVEAU TESTAMENT'),
('3 Jean', 'NOUVEAU TESTAMENT'),('Jude', 'NOUVEAU TESTAMENT'),
('Apocalypse', 'NOUVEAU TESTAMENT');

